apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtechno-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rtechno-backend
  template:
    metadata:
      labels:
        app: rtechno-backend
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: rtechno-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DEMO_MESSAGE
              value: "{{ .Values.env.DEMO_MESSAGE }}"
